### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by SVD6** [dharshatharan/dharsh.dev#22]
Looks like "developer" is spelled incorrectly.

<img width="531" alt="Screen Shot 2021-11-16 at 10 44 54 AM" src="https://user-images.githubusercontent.com/22820864/142017710-64f5c210-d356-46e4-a6ea-ca4c86ce5f97.png">

Also would recommend referring to the word "internet" with a capital "I" in your context. internet -> Internet

**Comment by dharshatharan** [comment]
Thanks a lot, Sai, for spotting this before some recruiter judges me for being a writer that can't spell developer 🤦‍♂️

I don't have a contribution guideline yet, but here are some pointers on how you can fix this yourself.

Prerequisites:
Ensure you have Node and NPM installed on your machine. Ideally one of the recent stable versions.
`Node: v16.13.0`
`npm: ^8.1.0`

Step 1:
Fork this repository 

Step 2:
Clone the forked repository on your machine

Step 3:
Create a new branch
`git checkout -b MY_BRANCH_NAME`

Step 4: 
Install Packages from project root directory
`cd dharsh.dev`
`npm install`

Step 5:
Run dev server
`npm run dev` - the application will be visible on `localhost:3000`

Step 6:
Make changes to the project and watch your changes appear on `localhost:3000`
In your case, it should all be in the `/pages/index.tsx` file

Step 7:
When done making changes, add and commit your changes to push them
 `git push origin new-feature` 

Step 8:
Create a pull request to the original repository!

I'm not sure there might be any hiccups along the way, so it would be great if you could try it out and document the process through issue #23 that I created about making `contributing.md` file.

Cheers!

**Comment by dharshatharan** [comment]
I was working on some updates to the website and ended up fixing this issue haha. I'm sure you can find more spelling mistakes somewhere though :)
