### ISSUE TITLE
Create contribution guideline

### ISSUE THREAD

**Issue by dharshatharan** [dharshatharan/dharsh.dev#23]
Currently, we do not have a guideline on how to contribute to this repository. It would be great to have a `contributing.md` file to guide people through the recommended process.

These are the general steps that one would have to follow, it would be great if we could confirm this and include them in the `contributing.md` file.

Prerequisites:
Ensure you have Node and NPM installed on your machine. Ideally one of the recent stable versions.
`Node: v16.13.0`
`npm: ^8.1.0`

Step 1:
Fork this repository 

Step 2:
Clone the forked repository on your machine

Step 3:
Create a new branch
`git checkout -b MY_BRANCH_NAME`

Step 4: 
Install Packages from project root directory
`cd dharsh.dev`
`npm install`

Step 5:
Run dev server
`npm run dev` - the application will be visible on `localhost:3000`

Step 6:
Make changes to the project and watch your changes appear on `localhost:3000`
In your case, it should all be in the `/pages/index.tsx` file

Step 7:
When done making changes, add and commit your changes to push them
 `git push origin new-feature` 

Step 8:
Create a pull request to the original repository!

**Comment by SVD6** [comment]
Can I claim this issue please?

**Comment by dharshatharan** [comment]
Done!
