### ISSUE TITLE
Can You share the Notion Doc of the Blogs Page?

### ISSUE THREAD

**Issue by hrithwikbharadwaj** [dharshatharan/dharsh.dev#26]
is it possible for you to please add the blogs notion page/DB in the readme so that folks can replicate that to create something similar when creating blogs ?

**Comment by dharshatharan** [comment]
For sure! That's a great idea. I can do that.

**Comment by dharshatharan** [comment]
I've added links to the actual blog database and a template you can duplicate to the readme. Hope it helps 😃

**Comment by hrithwikbharadwaj** [comment]
Thanks
