### ISSUE TITLE
TypeError: path__WEBPACK_IMPORTED_MODULE_1___default is not a function

### ISSUE THREAD

**Issue by hrithwikbharadwaj** [dharshatharan/dharsh.dev#27]
Getting this error when using mdx.js file

```
TypeError: path__WEBPACK_IMPORTED_MODULE_1___default is not a function
```

I think it's because of the getBundledMDX() function. What am I doing wrong ?

**Comment by dharshatharan** [comment]
Hey @hrithwikbharadwaj!

Can you give me more context on what you are trying to do here? Are you trying to run the code from this repo or are you trying to implement it on your own code base? It would be helpful if you give me steps to reproduce the bug or point me to the code that you're working on.

**Comment by hrithwikbharadwaj** [comment]
Hey,

I am trying to implement things from this code to my side-projects blog section which is a JavaScript Project. 

I have installed all modules like
```
"mdx-bundler": "^8.0.1",
  "@notionhq/client": "^0.4.13",
   "@tailwindcss/typography": "^0.4.1",
 "rehype-autolink-headings": "^6.1.1",
    "rehype-code-titles": "^1.0.3",
    "rehype-prism-plus": "^1.3.1",
    "rehype-slug": "^5.0.1",
    "remark-gfm": "^3.0.1",
```

I was able to get the list of blogs but not able to open the blog page , I think it's because of the process.env.ESBUILD_BINARY_PATH or the function getBundledMDX() . Can you please help me out

Edit: I think it's because of the esbuild too since I don't have esbuild installed . 

Edit2: It was because of ESbuild .

Thanks. Closing this

**Comment by dharshatharan** [comment]
Hey, yeah it might be that you don't have esbuild installed. As you can see I have `"esbuild": "^0.12.09"` installed. And don't worry aboue the ESBuildBinaryPath environment variable. I don't have it set on my .env file. As far as I know, that value will be set automatically by esbuild

**Comment by hrithwikbharadwaj** [comment]
Thanks for your time Dharsh.
